### ISSUE TITLE
NPE if there is no connection established.

### ISSUE THREAD

**Issue by hatahet** [CloudBees-community/syslog-java-client#3]
If I specify a hostname/port combination that does not result in a successful connection, a `NullPointerException` gets thrown when I call `sendMessage()`:
```
java.lang.NullPointerException: null
	at com.cloudbees.syslog.sender.TcpSyslogMessageSender.ensureSyslogServerConnection(TcpSyslogMessageSender.java:121) ~[syslog-java-client-1.0.3.jar:na]
	at com.cloudbees.syslog.sender.TcpSyslogMessageSender.sendMessage(TcpSyslogMessageSender.java:90) ~[syslog-java-client-1.0.3.jar:na]
	at com.cloudbees.syslog.sender.AbstractSyslogMessageSender.sendMessage(AbstractSyslogMessageSender.java:53) ~[syslog-java-client-1.0.3.jar:na]
	at com.cloudbees.syslog.sender.AbstractSyslogMessageSender.sendMessage(AbstractSyslogMessageSender.java:60) ~[syslog-java-client-1.0.3.jar:na]
```

I suspect there needs to be another `null` check in the `if` condition here: https://github.com/CloudBees-community/syslog-java-client/blob/master/src/main/java/com/cloudbees/syslog/sender/TcpSyslogMessageSender.java#L121

(e.g. `if (socket != null && socket.getInetAddress() != null && ...)`.

According to the [Java docs](http://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#getInetAddress%28%29):
>     the remote IP address to which this socket is connected, or null if the socket is not connected.

**Comment by cyrille-leclerc** [comment]
Release 1.0.4 with the fix has just been cut. I will soon be available in Maven Central Repo.

**Comment by hatahet** [comment]
Thank you for the quick turn around!

**Comment by cyrille-leclerc** [comment]
You're welcome!

By the way, could you share with us the context in which you use this library? in Jenkins? in a web app? ...

**Comment by hatahet** [comment]
@cyrille-leclerc we're using it in a security application to send alerts to log management systems.

**Comment by cyrille-leclerc** [comment]
Thanks for the details @hatahet
