### ISSUE TITLE
IllegalMonitorStateException when attempting to connect to hostname that does not resolve.

### ISSUE THREAD

**Issue by hatahet** [CloudBees-community/syslog-java-client#4]
For example, if I set the the syslog server hostname to `abc.def`, and use an arbitrary port, I see the following exception:
```
Caused by: java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:447)
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:431)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1340)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:883)
	at com.cloudbees.syslog.util.CachingReference.get(CachingReference.java:93)
	at com.cloudbees.syslog.sender.TcpSyslogMessageSender.ensureSyslogServerConnection(TcpSyslogMessageSender.java:121)
	at com.cloudbees.syslog.sender.TcpSyslogMessageSender.sendMessage(TcpSyslogMessageSender.java:91)
	at com.cloudbees.syslog.sender.AbstractSyslogMessageSender.sendMessage(AbstractSyslogMessageSender.java:53)
	at com.cloudbees.syslog.sender.AbstractSyslogMessageSender.sendMessage(AbstractSyslogMessageSender.java:60)
```

**Comment by cyrille-leclerc** [comment]
Release 1.0.5 has been publish, it should soon be available in Maven Central Repository.

**Comment by cyrille-leclerc** [comment]
Hello @hatahet, could you test the new release?

**Comment by hatahet** [comment]
Hi @cyrille-leclerc. I'll test it out as soon as it shows up in the Maven Repository: http://mvnrepository.com/artifact/com.cloudbees/syslog-java-client

**Comment by cyrille-leclerc** [comment]
Weird that is not yet in maven central, I'll check.

Cyrille Le Clerc
cleclerc@cloudbees.com +33-6.61.33.69.86

**Comment by cyrille-leclerc** [comment]
http://mvnrepository.com/ seem to have a sync issue. 
syslog-java-client-1.0.5 has been available on Maven Central Repository since "09-Feb-2015 04:21":

https://repo1.maven.org/maven2/com/cloudbees/syslog-java-client/1.0.5/

Cyrille

**Comment by hatahet** [comment]
@cyrille-leclerc 

Thanks for letting me know. I just tested it out, and it works as expected.
```
Caused by: java.lang.IllegalStateException: java.net.UnknownHostException: abc.def
	at com.cloudbees.syslog.sender.TcpSyslogMessageSender$1.newObject(TcpSyslogMessageSender.java:195)
	at com.cloudbees.syslog.sender.TcpSyslogMessageSender$1.newObject(TcpSyslogMessageSender.java:188)
```
Thank you so much again for the quick turn around time! :)

**Comment by cyrille-leclerc** [comment]
Thanks @hatahet !
